function get_signals(filepath,filename,can,msgField)
% Process each individual message (mi)
% msgField = fieldnames(can);
% msgField = {'ACCDATA';...
% 'ACCDATA_2'};%;...

% msgField = {'GPS_Data_Nav_1';...
% 'GPS_Data_Nav_2';...
% 'GPS_Data_Nav_3'};

% 'ACCDATA_3';...
% 'Accel_Data';...
% 'Battery_Mgmt_1';...
% 'Battery_Mgmt_2';...
% 'BrakeSnData_2';...
% 'BrakeSnData_3';...
% 'BrakeSnData_4';...
% 'BrakeSysFeatures';...
% 'BrakeSysFeatures_2';...
% 'DesiredTorqBrk';...
% 'EngBrakeData';...
% 'EngVehicleSpThrottle';...
% 'EngineData_1';...
% 'EngineData_13_CG1';...
% 'EngineData_2_CG1';...
% 'EngineData_3';...
% 'EngineData_4';...
% 'Engine_Data_2_MS';...
% 'Engine_Data_6';...
% 'Engine_Data_7';...
% 'Engine_Data_8';...
% 'Engine_Data_MS';...
% 'GPS_Data_Nav_1';...
% 'GPS_Data_Nav_2';...
% 'GPS_Data_Nav_3';...
% 'Ignition_Switch_PositionM';...
% 'MS_Steering_Data';...
% 'PowertrainData_1';...
% 'PowertrainData_2';...
% 'Side_Detect_CmdM';...
% 'Steering_Wheel_Data';...
% 'Tire_Pressure_Data';...
% 'TractionCtrlStatus';...
% 'TransData_1';...
% 'TransData_2';...
% 'TransData_3';...
% 'TransGearData';...
% 'TransGearData_2';...
% 'TransGearData_3';...
% 'TransGearData_4';...
% 'WheelSpeed';...
% 'Yaw_Data'};

%% 1) for each message:
for mi = 1:length(msgField)
    msgString = ['can.' msgField{mi}];
    if isfield(can, msgField(mi))
        msgStruct = fieldnames(eval(msgString));
        
        % Process each individual signal of each message (si)
        for si = 1:length(msgStruct)
            sgnString = ['can.' msgField{mi} '.' msgStruct{si}];
            sgnValue = eval(sgnString);
            
            % Write signal values to signal name including message_signal
            v=genvarname([msgField{mi} '_' msgStruct{si}],who);
            
            % mfallon change:
            eval( [v ' = sgnValue;']);
            %evalin('base', [v ' = sgnValue;']);
        end
    end
end
% messages = [msgField{mi} '_' msgStruct{si}];
% messages1 = [messages(1,:) '1'];
clear msgString si can msgStruct success mi sgnString v sgnValue

% fprintf('\n');
% fprintf('\n*************************************************\n');
% fprintf('All signals converted from a structure to arrays.');
% fprintf('\n*************************************************\n');


%% 2) Merge variables from previous file to new file [probably not required
%% any more)
merge2vars;


clear can
%%  3) Get lat/lon as a single set of numbers
if exist('GPS_Data_Nav_1_GPS_Latitude_Degrees','var')
    lat = gpsdegminmindec2deg(GPS_Data_Nav_1_GPS_Latitude_Degrees,...
        GPS_Data_Nav_1_GPS_Latitude_Minutes,GPS_Data_Nav_1_GPS_Latitude_Min_dec);
    lon = gpsdegminmindec2deg(GPS_Data_Nav_1_GPS_Longitude_Degrees,...
        GPS_Data_Nav_1_GPS_Longitude_Minutes,GPS_Data_Nav_1_GPS_Longitude_Min_dec);
end
%%  4) Unwrap time stamps
cat_timestamps;
%%  4.0) Save data to .mat file
% for new naming
%MyFileName = strcat(msgField{1},'_',f(1,1:length(f(1,:))-5), '_to_',f(length(f(:,1)),(length(f(1,:))-9):length(f(1,:))-5));
MyMatFileName = strcat([filepath filename(1:end-4) ], '.mat');
save(MyMatFileName, '*')
