#I/O function
import os
def write_gpx(file_f,file_t,line_s,line_e):
    writer=open(file_t,'w') 
    writer.write("""<?xml version="1.0" encoding="utf-8"?><gpx><trk><trkseg>\n""")
    writer.close()
    os.popen("sed -n '"+str(line_s)+","+str(line_e)+"p' '"+file_f+"' >>'"+file_t+"'")
    #print "sed -n '"+str(line_s)+","+str(line_e)+"p' '"+file_f+"' >>'"+file_t+"'"
    os.popen("echo '</trkseg></trk></gpx>' >> '"+file_t+"'")

"""
def write_route(file_t,record,ways):
    writer=open(file_t,'w') 
    for rr in record:
        writer.write(str(rr[2])+","+ways[rr[2]].name+","+str(rr[3])+","+str(rr[4])+"\n")
        #writer.write(ways[rr[2]].name+","+str(rr[3])+","+str(rr[4])+"\n")
    writer.close()
"""
def write_route(file_t,record,ways,nodes):
    writer=open(file_t,'w') 
    for i in range(len(record)-1):
        rr=record[i]
        writer.write(str(rr[2])+","+ways[rr[2]].name+","+str(rr[1])+","+str(nodes[ways[rr[2]].nd[0]].lat)+","+str(nodes[ways[rr[2]].nd[0]].lon)+","+str(record[i+1][1]-1)+","+str(nodes[ways[rr[2]].nd[-1]].lat)+","+str(nodes[ways[rr[2]].nd[-1]].lon)+"\n")
    writer.close()

def readgpx(file_f):
    a=open(file_f)
    line=a.readline().lstrip()
    pt=[]
    while line!='':
        line=a.readline().lstrip()
        if 'lat=' in line:        
            pt.append((float(line[line.find('lat="')+5:line.find('" lon')]),float(line[line.rfind('lon="')+5:line.find('">')])))
    a.close()
    return pt
class Constant:
    roadtype=[
                            'primary',
                            'secondary',                            
                            'tertiary',
                            'residential',
                            'trunk',
                            'motorway'
                            ]    
    # 'trunk_link','primary_link','secondary_link','unclassified','tertiary_link',
    renderingRules = {
        'primary': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 10,
                color           = (0.7,0.7,1.0,0.1),
                alpha           = 1.0,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -1,
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 8,
                _firstzorder          = 1,   
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,
                _lastzorder           = 0,   
                ),
        'primary_link': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 8,
                color           = (0.7,0.7,1.0,0.1),
                alpha           = 1.0,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -1,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 12,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),
        'secondary': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 6,
                color           = (0.2,0.2,0.7,0.1),
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -2,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 10,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),
        'secondary_link': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 6,
                color           = (0.2,0.2,0.7,0.1),
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -2,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 10,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),
        'tertiary': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 4,
                color           = (0.0,0.0,0.7,0.1),
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -3,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 10,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),
        'tertiary_link': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 4,
                color           = (0.0,0.0,0.7,0.1),
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -3,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 10,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),
        'residential': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 1,
                color           = (0.1,0.1,0.1,1.0),
                alpha           = 1.0,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -99,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 10,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 8,   
                _lastzorder           = 0, 
                ),            
        'unclassified': dict(
                marker          = 'D',
                markeredgecolor = (0.5,0.5,0.5),
                markeredgewidth = 1,
                markerfacecolor = (0.5,0.5,0.5), 
                markersize      = 2,                   
                linestyle       = ':',
                linewidth       = 1,
                color           = (0.5,0.5,0.5),
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -1,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'g',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'g', 
                _firstmarkersize      = 6,   
                _firstzorder          = 1,            
                _lastmarker           = 'o',
                _lastmarkeredgecolor  = 'r',
                _lastmarkeredgewidth  = 1,
                _lastmarkerfacecolor  = 'r', 
                _lastmarkersize       = 6,   
                _lastzorder           = 0,             
                ),
        'default': dict(
                marker          = 'D',
                markeredgecolor = 'b',
                markeredgewidth = 1,
                markerfacecolor = 'b', 
                markersize      = 2,                   
                linestyle       = '-',
                linewidth       = 3,
                color           = 'b',
                alpha           = 0.5,
                solid_capstyle  = 'round',
                solid_joinstyle = 'round',
                zorder          = -1,            
                markerzorder    = 0,
                _firstmarker          = 'x',
                _firstmarkeredgecolor = 'b',
                _firstmarkeredgewidth = 1,
                _firstmarkerfacecolor = 'b', 
                _firstmarkersize      = 6,   
                _firstzorder          = 1,              
                _lastmarker     = 'o',
                _lastmarkeredgecolor = 'b',
                _lastmarkeredgewidth = 1,
                _lastmarkerfacecolor = 'b', 
                _lastmarkersize      = 6,  
                _lastzorder           = 0,                     
                ),
        }

